In [34]:
import pandas as pd

In [35]:
df= pd.read_csv(r"C:\Users\Admin\Downloads\archive\Student Depression Dataset.csv")
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [36]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), object(8)
memory usage: 3.8+ MB

In [38]:
df.shape

(27901, 18)

In [39]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.isna().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [42]:
df['Financial Stress'].fillna(df['Financial Stress'].mode()[0], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19296\4236355950.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Financial Stress'].fillna(df['Financial Stress'].mode()[0], inplace=True)

In [43]:
df.drop(columns=['id'], inplace=True)

In [44]:
df.drop(columns=['Work Pressure'], inplace= True)

In [45]:
df.drop(columns=['Job Satisfaction'], inplace= True)

In [46]:
df.drop(columns=['Dietary Habits'], inplace= True)

In [47]:
df['Sleep Duration'].unique()

array(['5-6 hours', 'Less than 5 hours', '7-8 hours', 'More than 8 hours',
       'Others'], dtype=object)

In [48]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

encoder = OrdinalEncoder()
df['Gender_encoded'] = encoder.fit_transform(df[['Gender']])

In [49]:
df

,Gender,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Gender_encoded
0,Male,33.0,Visakhapatnam,Student,5.0,8.97,2.0,5-6 hours,B.Pharm,Yes,3.0,1.0,No,1,1.0
1,Female,24.0,Bangalore,Student,2.0,5.90,5.0,5-6 hours,BSc,No,3.0,2.0,Yes,0,0.0
2,Male,31.0,Srinagar,Student,3.0,7.03,5.0,Less than 5 hours,BA,No,9.0,1.0,Yes,0,1.0
3,Female,28.0,Varanasi,Student,3.0,5.59,2.0,7-8 hours,BCA,Yes,4.0,5.0,Yes,1,0.0
4,Female,25.0,Jaipur,Student,4.0,8.13,3.0,5-6 hours,M.Tech,Yes,1.0,1.0,No,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,Female,27.0,Surat,Student,5.0,5.75,5.0,5-6 hours,Class 12,Yes,7.0,1.0,Yes,0,0.0
27897,Male,27.0,Ludhiana,Student,2.0,9.40,3.0,Less than 5 hours,MSc,No,0.0,3.0,Yes,0,1.0
27898,Male,31.0,Faridabad,Student,3.0,6.61,4.0,5-6 hours,MD,No,12.0,2.0,No,0,1.0
27899,Female,18.0,Ludhiana,Student,5.0,6.88,2.0,Less than 5 hours,Class 12,Yes,10.0,5.0,No,1,0.0
27900,Male,27.0,Patna,Student,4.0,9.24,1.0,Less than 5 hours,BCA,Yes,2.0,3.0,Yes,1,1.0

In [50]:
df = df.drop('Gender', axis=1)

In [51]:
df

,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Gender_encoded
0,33.0,Visakhapatnam,Student,5.0,8.97,2.0,5-6 hours,B.Pharm,Yes,3.0,1.0,No,1,1.0
1,24.0,Bangalore,Student,2.0,5.90,5.0,5-6 hours,BSc,No,3.0,2.0,Yes,0,0.0
2,31.0,Srinagar,Student,3.0,7.03,5.0,Less than 5 hours,BA,No,9.0,1.0,Yes,0,1.0
3,28.0,Varanasi,Student,3.0,5.59,2.0,7-8 hours,BCA,Yes,4.0,5.0,Yes,1,0.0
4,25.0,Jaipur,Student,4.0,8.13,3.0,5-6 hours,M.Tech,Yes,1.0,1.0,No,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,27.0,Surat,Student,5.0,5.75,5.0,5-6 hours,Class 12,Yes,7.0,1.0,Yes,0,0.0
27897,27.0,Ludhiana,Student,2.0,9.40,3.0,Less than 5 hours,MSc,No,0.0,3.0,Yes,0,1.0
27898,31.0,Faridabad,Student,3.0,6.61,4.0,5-6 hours,MD,No,12.0,2.0,No,0,1.0
27899,18.0,Ludhiana,Student,5.0,6.88,2.0,Less than 5 hours,Class 12,Yes,10.0,5.0,No,1,0.0
27900,27.0,Patna,Student,4.0,9.24,1.0,Less than 5 hours,BCA,Yes,2.0,3.0,Yes,1,1.0

In [52]:
df[['Sleep Duration']]

          Sleep Duration
0              5-6 hours
1              5-6 hours
2      Less than 5 hours
3              7-8 hours
4              5-6 hours
...                  ...
27896          5-6 hours
27897  Less than 5 hours
27898          5-6 hours
27899  Less than 5 hours
27900  Less than 5 hours

[27901 rows x 1 columns]

In [53]:
df.columns

Index(['Age', 'City', 'Profession', 'Academic Pressure', 'CGPA',
       'Study Satisfaction', 'Sleep Duration', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression',
       'Gender_encoded'],
      dtype='object')

In [54]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df['Age'] = scaler.fit_transform(df[['Age']])

df.head()

,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Gender_encoded
0,1.463165,Visakhapatnam,Student,5.0,8.97,2.0,5-6 hours,B.Pharm,Yes,3.0,1.0,No,1,1.0
1,-0.371474,Bangalore,Student,2.0,5.90,5.0,5-6 hours,BSc,No,3.0,2.0,Yes,0,0.0
2,1.055467,Srinagar,Student,3.0,7.03,5.0,Less than 5 hours,BA,No,9.0,1.0,Yes,0,1.0
3,0.443921,Varanasi,Student,3.0,5.59,2.0,7-8 hours,BCA,Yes,4.0,5.0,Yes,1,0.0
4,-0.167625,Jaipur,Student,4.0,8.13,3.0,5-6 hours,M.Tech,Yes,1.0,1.0,No,0,0.0

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split

target_col = 'Depression'
cols_to_drop = ['id', 'Sleep Duration', 'Gender', 'Job Satisfaction', 'Work Pressure', 'Depression']

X = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
y = df['Depression']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
le_family = LabelEncoder()
df['Family History of Mental Illness'] = df['Family History of Mental Illness'].fillna(df['Family History of Mental Illness'].mode()[0])
df['Family History of Mental Illness'] = le_family.fit_transform(df['Family History of Mental Illness'])

In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import L1, L2
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import SGD, Adam

In [58]:
cat_cols = list(X_train.select_dtypes(include=['object']).columns)

encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

X_train[cat_cols] = encoder.fit_transform(X_train[cat_cols])
X_test[cat_cols] = encoder.transform(X_test[cat_cols])

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    
    Dense(50, activation='relu', input_shape=(X_train.shape[1],)), 
    Dense(40, activation='relu'), 
    Dense(1, activation='sigmoid') 
])

opt = SGD(learning_rate=0.01, momentum=0.9)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train, y_train, 
    epochs=20, 
    validation_split=0.1, 
    batch_size=32, 
    callbacks=[early_stopping]
)

model.summary()

C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.7430 - loss: 0.5308 - val_accuracy: 0.7809 - val_loss: 0.5093
Epoch 2/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8156 - loss: 0.4136 - val_accuracy: 0.8199 - val_loss: 0.3997
Epoch 3/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.8175 - loss: 0.4118 - val_accuracy: 0.8436 - val_loss: 0.3642
Epoch 4/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.8268 - loss: 0.3968 - val_accuracy: 0.8320 - val_loss: 0.3833
Epoch 5/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8306 - loss: 0.3876 - val_accuracy: 0.7966 - val_loss: 0.4412
Epoch 6/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.8313 - loss: 0.3851 - val_accuracy: 0.8436 - val_loss: 0.3637
Epoch 7/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - accuracy: 0.8335 - loss: 0.3832 - val_accuracy: 0.8374 - val_loss: 0.3955
Epoch 8/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - accuracy: 0.8352 - loss: 0.3775 - val_accuracy: 0.8289 - val_loss: 0.3703
Epoch 9/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.8355 - loss: 0.3789 - val_accuracy: 0.7944 - val_loss: 0.4393
Epoch 10/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.8370 - loss: 0.3780 - val_accuracy: 0.8392 - val_loss: 0.3741
Epoch 11/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.8337 - loss: 0.3800 - val_accuracy: 0.8392 - val_loss: 0.3635
Epoch 12/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.8349 - loss: 0.3795 - val_accuracy: 0.8262 - val_loss: 0.3892
Epoch 13/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.8379 - loss: 0.3753 - val_accuracy: 0.8450 - val_loss: 0.3606
Epoch 14/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.8374 - loss: 0.3755 - val_accuracy: 0.8405 - val_loss: 0.3706
Epoch 15/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.8372 - loss: 0.3766 - val_accuracy: 0.8423 - val_loss: 0.3601
Epoch 16/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8380 - loss: 0.3725 - val_accuracy: 0.8414 - val_loss: 0.3575
Epoch 17/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.8347 - loss: 0.3759 - val_accuracy: 0.8414 - val_loss: 0.3794
Epoch 18/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.8382 - loss: 0.3726 - val_accuracy: 0.8387 - val_loss: 0.3770
Epoch 19/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.8393 - loss: 0.3735 - val_accuracy: 0.8360 - val_loss: 0.3594
Epoch 20/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8375 - loss: 0.3734 - val_accuracy: 0.7975 - val_loss: 0.4134

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 50)             │           650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 40)             │         2,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,464 (21.35 KB)

 Trainable params: 2,731 (10.67 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,733 (10.68 KB)

In [60]:
opt = SGD(learning_rate=0.01, momentum=0.9)

model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train, y_train, 
    epochs=20, 
    validation_split=0.1, 
    batch_size=32, 
    callbacks=[early_stopping]
)

Epoch 1/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.8367 - loss: 0.3727 - val_accuracy: 0.8289 - val_loss: 0.3678
Epoch 2/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.8406 - loss: 0.3696 - val_accuracy: 0.8432 - val_loss: 0.3616
Epoch 3/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8400 - loss: 0.3709 - val_accuracy: 0.8374 - val_loss: 0.3602
Epoch 4/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.8394 - loss: 0.3726 - val_accuracy: 0.8454 - val_loss: 0.3603
Epoch 5/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.8379 - loss: 0.3721 - val_accuracy: 0.8441 - val_loss: 0.3564
Epoch 6/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.8405 - loss: 0.3704 - val_accuracy: 0.8436 - val_loss: 0.3723
Epoch 7/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8393 - loss: 0.3711 - val_accuracy: 0.8427 - val_loss: 0.3563
Epoch 8/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.8409 - loss: 0.3698 - val_accuracy: 0.8356 - val_loss: 0.3664
Epoch 9/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - accuracy: 0.8416 - loss: 0.3715 - val_accuracy: 0.8338 - val_loss: 0.3829
Epoch 10/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.8381 - loss: 0.3713 - val_accuracy: 0.8320 - val_loss: 0.3869
Epoch 11/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8402 - loss: 0.3712 - val_accuracy: 0.8409 - val_loss: 0.3615
Epoch 12/20
628/628 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - accuracy: 0.8388 - loss: 0.3709 - val_accuracy: 0.8409 - val_loss: 0.3624

In [61]:
model.evaluate(X_test, y_test)

175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.8309 - loss: 0.3835

[0.3835241496562958, 0.8308547139167786]

In [62]:
model.evaluate(X_train, y_train)

698/698 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.8438 - loss: 0.3591

[0.35907986760139465, 0.8437724113464355]